#!/bin/bash
age=15

if [ $age -gt 18 ]
then
echo "You are an adult!"
else
echo "You are not an adult!"
fi



score=85

if [ $score -ge 90 ]
then
    echo "Excellent!"
    
elif [ $score -ge 80 ]
then
    echo "Good!"
else
    echo "Better luck next time!"
    fi